[phases.setup]
nixPkgs = ["openjdk21", "maven"]

[phases.install]
cmds = [
  "cd EventsPortal-Backend",
  "chmod +x mvnw",
  "./mvnw dependency:go-offline -B"
]

[phases.build]
cmds = [
  "cd EventsPortal-Backend",
  "./mvnw clean package -DskipTests"
]

[start]
cmd = "cd EventsPortal-Backend && java -jar target/EventsPortal-Backend-0.0.1-SNAPSHOT.jar" 